# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: tf-deployment
version: 1.0.0
summary: Azure resources deployment using Terraform
description: Deploys a storage account, three network security groups, a log analytics workspace
runner: "acr0915.azurecr.io/ade-tfm:1.0.2"
templatePath: main.tf