# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: tf-deployment
version: 1.0.0
summary: Azure resources deployment using Terraform
description: Deploys a storage account with RBAC authentication, three network security groups, and a log analytics workspace
runner: "pltengacr01.azurecr.io/ade/terraform:0.0.2"
templatePath: main.tf
parameters:
  - id: rbac_storage_account_prefix
    name: rbac_storage_account_prefix
    description: Prefix for the RBAC-authenticated storage account name
    default: "rbacsta"
    type: string
  - id: web-nsg
    name: web-nsg
    description: Web network security group name
    default: "web-nsg"
    type: string
  - id: app-nsg
    name: app-nsg
    description: App network security group name
    default: "app-nsg"
    type: string
  - id: dta-nsg
    name: dta-nsg
    description: Data network security group name
    default: "dta-nsg"
    type: string
  - id: logAnalyticsWorkspaceName
    name: logAnalyticsWorkspaceName
    description: Log Analytics workspace name
    default: "arm-law-01"
    type: string
