# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: tf-deployment
version: 1.0.0
summary: Azure resources deployment using Terraform
description: Deploys a storage account, three network security groups, a log analytics workspace
runner: "acr0915.azurecr.io/ade-tfm:1.0.2"
templatePath: main.tf
parameters:
  - id: storageAccountPrefix
    name: storageAccountPrefix
    description: Prefix for the storage account name
    default: "1sta"
    type: string
  - id: web_nsg
    name: web_nsg
    description: Web network security group name
    default: "web-nsg"
    type: string
  - id: app_nsg
    name: app_nsg
    description: App network security group name
    default: "app-nsg"
    type: string
  - id: dta_nsg
    name: dta_nsg
    description: Data network security group name
    default: "dta-nsg"
    type: string
  - id: logAnalyticsWorkspaceName
    name: logAnalyticsWorkspaceName
    description: Log Analytics workspace name
    default: "arm-law-01"
    type: string